### PR TITLE
bump to ember 1.13.4

### PR DESCRIPTION
**Pull request by stefanpenner**
1 failing test, will investigate.

### CODE REVIEW

**Comment by stefanpenner** [comment]
hmm I consistently get an error in tests in chrome... It appears to be a race condition, and from the looks of it maybe an ember issue.

Headless tests appear to be good though..

**Comment by Gaurav0** [comment]
Looks good to me.

**Comment by stefanpenner** [comment]
Note: once this is deployed I can publish the component less helpers as a twiddle

**Comment by Gaurav0** [comment]
@stefanpenner You can start writing your gist on my branch at https://ember-twiddle-gaurav.herokuapp.com

**Comment by stefanpenner** [comment]
> @stefanpenner You can start writing your gist on my branch at https://ember-twiddle-gaurav.herokuapp.com

:P

**Comment by stefanpenner** [comment]
)

**Pull request merged**
