### PR TITLE
Backward compatible with old names

### PR DESCRIPTION
**Pull request by Gaurav0**

### CODE REVIEW

**Comment by rwjblue** [comment]
This looks perfect for default exports, can you also add support for named exports?

**Comment by Gaurav0** [comment]
@rwjblue done.

**Comment by rwjblue** [comment]
Awesome, thank you!   Does that support `import a, { b, c } from "demo-app/b";`?  I can't tell by just glancing at the regexp...

**Comment by Gaurav0** [comment]
I'll add a test.

**Comment by Gaurav0** [comment]
@rwjblue done. Any others you can think of?

**Comment by rwjblue** [comment]
Hmm, maybe multiline?

```
import {
  a,
  b,
  c
} from 'demo-app/utils';
```

**Comment by joostdevries** [comment]
@Gaurav0 wouldn't this cover all:

```javascript
var r = new RegExp(`import ([^]+?) from (\'|\")${oldName}/`,'gmi');
```

**Comment by Gaurav0** [comment]
@joostdevries Doesn't work

**Pull request merged**
