### PR TITLE
Change app name to twiddle

### PR DESCRIPTION
**Pull request by Gaurav0**

### CODE REVIEW

**Comment by joostdevries** [comment]
lgtm

**Comment by rwjblue** [comment]
Hmm.  Does this break the addon processing?  I suspect that it needs to build the addons with the same app name...

**Comment by joostdevries** [comment]
@rwjblue that's the reason for the change ;-)

**Comment by rwjblue** [comment]
@joostdevries - And the cache of prebuilt addons was cleared?

**Comment by joostdevries** [comment]
@rwjblue Yes. Because the build process was completely refactored to use docker instead of lambda (allowing git deps and muuuch faster build times and lower costs).

**Comment by alexspeller** [comment]
Wait, am I missing something or will this break all existing twiddled that
have imports in them for local modules?

**Comment by joostdevries** [comment]
@alexspeller the name was recently changed from `demo-app` to `app` so that breakage was already present at that point AFAIK.

**Comment by rwjblue** [comment]
We should detect the twiddle.json version, and use the appropriate name.

**Comment by joostdevries** [comment]
@rwjblue agreed but prefer to track that in isolated issue since breakage was already introduced.

**Comment by Gaurav0** [comment]
@alexspeller It doesn't break imports that use relative urls.

**Comment by joostdevries** [comment]
@rwjblue https://github.com/ember-cli/ember-twiddle/issues/41

**Comment by rwjblue** [comment]
> so that breakage was already present at that point AFAIK

The change from `demo-app` to `app` was over 10 days ago (released in https://github.com/ember-cli/ember-twiddle/releases/tag/v0.7.2 5 days ago).  Anyone bit by this, likely now has to deal with this twice.

This tool is a large community resource, and should follow the same guidelines on breakages as Ember itself.  The change to `app` should have been reverted as soon as it was clear that this broke existing twiddles and the solution I proposed (and you created #41 to track) should have been implemented **before** introducing yet another breaking change.

**Comment by joostdevries** [comment]
@rwjblue agreed. Let's hold off on releasing untill we fix #41

**Comment by joostdevries** [comment]
or revert to `demo-app`

**Comment by joostdevries** [comment]
@Gaurav0 we could also just do a very simple `replace(/demo-app/g, "twiddle")` in the UI only I guess

**Pull request merged**
