### PR TITLE
Use my new deploy pack for s3

### PR DESCRIPTION
**Pull request by Gaurav0**

### CODE REVIEW

**Comment by rwjblue** [comment]
What is the main difference here?  Does the pack just bundle these packages together?

**Comment by Gaurav0** [comment]
Yes!

**Comment by joostdevries** [comment]
@rwjblue http://ember-cli.com/ember-cli-deploy/docs/v0.5.x/plugin-packs/

**Comment by joostdevries** [comment]
:+1: lgtm

**Pull request merged**
