### PR TITLE
Specify open files via query paramter

### PR DESCRIPTION
**Pull request by Gaurav0**
This is for issue #123.

### CODE REVIEW

**Comment by stefanpenner** [comment]
Should link-to that changes the query param open then files in question? Or is that out of scope

**Comment by Gaurav0** [comment]
@stefanpenner I think that should already work. Let me check.

**Comment by Gaurav0** [comment]
@stefanpenner A link-to within the outer application does indeed open the files. You can't do it from the twiddle itself, though. And I think that is ok.

**Comment by stefanpenner** [comment]
> @stefanpenner A link-to within the outer application does indeed open the files. You can't do it from the twiddle itself, though. And I think that is ok.

:+1: sounds great.

**Comment by alexspeller** [comment]
:tada:

**Pull request merged**
