### PR TITLE
Adds context menu

### PR DESCRIPTION
**Pull request by gokatz**

### CODE REVIEW

**Comment by Gaurav0** [comment]
@gokatz status?

**Comment by gokatz** [comment]
Things are pretty tight for a while, @Gaurav0. Will spend some time over this weekend and get this merged.

**Comment by gokatz** [comment]
triggering the "contextmenu" event in the test opens the menu after the test finishes, any idea about this behaviour @Gaurav0 ?

**Comment by knownasilya** [comment]
Maybe isn't waitFor/waitUntil on a selector of the menu?

**Comment by gokatz** [comment]
Yeah I tried both and also some custom context menu event dispatcher instead of the built-in triggerEvent. Still no luck.

**Comment by gokatz** [comment]
It turns out `contextmenu` was appended to the whole document not withing the testing app container. Used `document.querySelectorAll` instead of `qunit-dom` APIs to test the changes.

**Pull request merged**
