### PR TITLE
update ember and ember-data versions

### PR DESCRIPTION
**Pull request by GavinJoyce**
partial fix for https://github.com/ember-cli/ember-twiddle/issues/560 and https://github.com/ember-cli/ember-twiddle/issues/563

It looks like we'll also have to update https://github.com/joostdevries/twiddle-backend

### CODE REVIEW

**Comment by GavinJoyce** [comment]
Ember 2.14, 2.15 & 2.16: https://github.com/joostdevries/twiddle-backend/pull/30

**Comment by GavinJoyce** [comment]
Test failure seems unrelated to this change:

```
not ok 32 Chrome - error
    ---
        message: >
            Error: Browser disconnected
            Stderr: 
             Xlib:  extension "RANDR" missing on display ":99.0".
            
            (google-chrome:7816): LIBDBUSMENU-GLIB-WARNING **: Unable to get session bus: Unknown or unsupported transport 'disabled' for address 'disabled:'
            ATTENTION: default value of option force_s3tc_enable overridden by environment.
            [7888:7888:1027/202940.633546:ERROR:sandbox_linux.cc(346)] InitializeSandbox() called with multiple threads in process gpu-process.
            
            #
            # Fatal process OOM in heap setup
            #
            
            
            
        Log: |
            { type: 'error', text: 'Error: Browser disconnected' }
            { type: 'error',
              text: 'Xlib:  extension "RANDR" missing on display ":99.0".\n\n(google-chrome:7816): LIBDBUSMENU-GLIB-WARNING **: Unable to get session bus: Unknown or unsupported transport \'disabled\' for address \'disabled:\'\nATTENTION: default value of option force_s3tc_enable overridden by environment.\n[7888:7888:1027/202940.633546:ERROR:sandbox_linux.cc(346)] InitializeSandbox() called with multiple threads in process gpu-process.\n\n#\n# Fatal process OOM in heap setup\n#\n\n' }
```

**Comment by efx** [comment]
That error stems from using [xvfb](https://www.x.org/releases/X11R7.7/doc/man/man1/Xvfb.1.xhtml). Updating this project's ember-cli version should include a more reliable way to launch the headless tests. (headless chrome)
Getting this and updates to available ember versions is needed to quickly reproduce bugs based on latest branches. Right now the [contributer workflow](https://github.com/emberjs/data/blob/master/CONTRIBUTING.md#reporting-a-bug) for reporting an issue in ember and/or data is somewhat broken.

**Comment by Gaurav0** [comment]
Merged!

**Pull request closed without merging**
