### PR TITLE
Add MIT license

### PR DESCRIPTION
**Pull request by alexspeller**
@JKGisMe asked about the license, I realised I forgot to license as MIT when creating it. So I'm filing a PR to add this license.

I am tagging all contributors, as technically the code you contributed is still copyrighted to you so I don't have the right to unilaterally license it as MIT after the fact. Any objections, please let me know in the comments. I will leave this PR up for a period of one week, after which I will assume you are OK with this license and merge it.

@Gaurav0 @joostdevries @pangratz @alexspeller @JKGisMe @rwjblue @miguelcobain @HeroicEric @piotrpalek @brianally @kagemusha @grapho @makepanic @knownasilya @stefanpenner @koriroys @bcardarella @jpadilla @SaladFork @phkavitha @acorncom @vikram7 @tim-evans

### CODE REVIEW

**Comment by tim-evans** [comment]
Fine with me~

**Comment by stefanpenner** [comment]
:+1:

**Comment by koriroys** [comment]
:sparkles: :+1: :sparkles:

**Comment by acorncom** [comment]
:+1:

**Comment by vikram7** [comment]
:smile_cat:

**Comment by pangratz** [comment]
:+1:

**Comment by Gaurav0** [comment]
:+1:

**Comment by HeroicEric** [comment]
:+1:

**Comment by joostdevries** [comment]
:+1:

**Comment by knownasilya** [comment]
:+1:

**Comment by SaladFork** [comment]
:+1:

**Comment by jpadilla** [comment]
:+1:

**Comment by miguelcobain** [comment]
Of course :+1:

A qui, 12/11/2015, 15:03, José Padilla <notifications@github.com> escreveu:

**Comment by JKGisMe** [comment]
:+1:

**Comment by grapho** [comment]
Go for it!

**Comment by piotrpalek** [comment]
:+1:

**Comment by bcardarella** [comment]
I'm merging this so I can stop getting the emails

**Comment by stefanpenner** [comment]
screen shot 2015-11-13 at 8 23 41 am

**Pull request merged**
