### PR TITLE
Fix title width

### PR DESCRIPTION
**Pull request by JKGisMe**
Just reserves the `<span class='user-avatar'>` space whether there is a user logged in or not to keep styling consistent. It appears to successfully stop the title from getting cut off.

### CODE REVIEW

**Comment by JKGisMe** [comment]
(had a little rebase adventure so let me know if I need to fix anything)

**Comment by Gaurav0** [comment]
Given the small change, it might just be easiest for all if you recreate the branch from master

**Comment by Gaurav0** [comment]
I was able to git cherry-pick the commit.

**Comment by JKGisMe** [comment]
Thanks, I'm trying to figure out how to use git more like other people do and going through some growing pains with it.

**Pull request closed without merging**
