### PR TITLE
Use protocol-relative urls in the dependency resolver

### PR DESCRIPTION
**Pull request by joostdevries**

### CODE REVIEW

**Comment by jamesarosen** [comment]
Provided this is always used in a browser (as opposed to in pure Node), +1

**Comment by joostdevries** [comment]
@jamesarosen @stefanpenner @Gaurav0 if tests pass I'm fine with this :-)

**Comment by Gaurav0** [comment]
:+1: :)

**Comment by Gaurav0** [comment]
Damn. The other links work, but release, beta, and canary do not.

**Pull request merged**
