### PR TITLE
CSS fixes and improvements

### PR DESCRIPTION
**Pull request by piotrpalek**
The main issue I was trying to fix is that the "Run Tests" and "Live Reload" checkboxes cover each other when "Live Reload" is deselected:
Before:
image
After:
image

Other problems this will fix (discovered while fixing the first issue):
- the header elements are consistently positioned (especially vertically) across all panes (esp. visible for eg. the on "Output" string):
Before:
image
After:
image

- [when the tree is hidden and there are 0 editor panes](https://ember-twiddle.com/?fileTreeShown=false&numColumns=0) the page looked broken:
Before:
image
After:
image

- I've changed how the file tree looks and behaves, it is no longer resizable and is much smaller which leaves more space for the important stuff (it still expands when the tree shifts to the right due to many items):
Before:
image
After:
image

Mobile view (only last screen has real changes so I provide a "before" screenshot there):
image
image

Fixed output pane:
Before:
image
After:
image

Edit: I think I'd add a little more spacing to the file tree (left/right) looks a bit too cramped together imo

### CODE REVIEW

**Comment by Gaurav0** [comment]
1. Please don't make the file tree unresizable. Making it smaller by default would be fine.
2. Please post mobile screenshots after changes.

**Comment by piotrpalek** [comment]
@Gaurav0 Regarding #1 what's the utility of being able to resize the file tree?

**Comment by piotrpalek** [comment]
@Gaurav0 I've updated the description with mobile screenhots. The changes are also visible [here](http://twiddlefork.herokuapp.com/)

**Comment by piotrpalek** [comment]
@Gaurav0 noticed one more issue, the filepane behaves a bit weirdly when trying to shrink it below the minimum width (instead of nothing happening, the panel next to the filepane starts to grow). Let me fix that before merging.

**Comment by piotrpalek** [comment]
@Gaurav0 I've fixed the tree issue and some additional ones:

- added a scrollbar when the filepanes contents are too big
Before:
image
After:
image

- the top toolbar was broken in mobile view when the text was too long (for eg. when displaying the revision)
Before:
image
After:
image

**Comment by Gaurav0** [comment]
Looks Awesome. Thanks!

**Pull request merged**
